### ISSUE TITLE
Bug: Client getting mixed up with particular PTIF that doesn't have exactly 50% of next larger resolution

### ISSUE THREAD

**Issue by beaudet** [ruven/iipmooviewer#73]
With the latest VIPS that rounds resolutions of pages to avoid clipping data from the image, there appears to be an IIPMooviewer client (Ruven thinks likely) issue with calculating the TIL coordinates.  The server seems to be rendering the proper data for the given tile.

Screenshot below and I e-mailed Ruven a link so he can download the PTIF causing the problem.

![image](https://user-images.githubusercontent.com/77699/27181409-88d1fe9e-51a5-11e7-8485-cc43a332059e.png)

**Comment by beaudet** [comment]
Some discussion about this also present here: https://github.com/jcupitt/libvips/issues/659

**Comment by jcupitt** [comment]
Some background: currently vips always rounds down when sizing pyramid layers. Layers are sized by something like:

```ruby
width = 13246234
while width > tile_width do
   puts "width = #{width}"
  width = (width / 2.0).floor
end
```

There's a proposal to change this to something like:

```ruby
width = 13246234
while width > tile_width do
   puts "width = #{width}"
  width = (width / 2.0).ceil
end
```

So some layers will be one pixel wider. This can fix some slightly annoying clipping in some circumstances.

It seems `iipmooviewer` asks for tiles by tile index rather than (x, y) coordinate, so if the way that `iipmooviewer` sizes layers doesn't exactly match vips's, you see messed up tiles as above.

Does the iip spec mandate round down? Or should mooviewer check the size of each layer in the image when it opens it?

**Comment by beaudet** [comment]
Currently, it appears that IIPMooviewer makes only one metadata call per zoom session and that the data returned from that call is insufficient to ascertain the resolution of each tile.    That is, in the example below, while IIP server knows there's a one pixel wide tile at res 3, tile 6, iip mooviewer doesn't because it's using floor() and thinks tile 6 starts a new row.

$ curl "https://media.nga.gov/fastcgi/iipsrv.fcgi?FIF=/public/objects/5/2/4/5/0/52450-primary-0-nativeres.ptif&obj=IIP,1.0&obj=Max-size&obj=Tile-size&obj=Resolution-number"
IIP:1.0
Max-size:5121 3459
Tile-size:256 256
Resolution-number:6

Presumably the IIP protocol is sufficient such that making additional metadata requests for zoom level resolutions is possible.

e.g.

**Comment by ruven** [comment]
Yes, it would be easy to make iipmooviewer obtain a full list of resolutions. I'll look into how best to do that. It may require implementing a new command server-side also

**Comment by beaudet** [comment]
Thanks Ruven.

**Comment by beaudet** [comment]
Did I understand correctly that the IIP Mooviewer also supports the IIIF protocol?  If so, how would one enable that for testing purposes?  That might provide the shortest path to resolution if that's the case since info.json provides the resolutions already.

**Comment by ruven** [comment]
Include the iiif.js protocol:

`  <script type="text/javascript" src="src/protocols/iiif.js"></script>`

Then set the protocol parameter to "iiif" in the constructor like this:

```
var iipmooviewer = new IIPMooViewer( 'viewer',{
  ...
  protocol: 'iiif'
};
```
It'll need to parse the info.json file and populate the array _this.resolutions_ with the correct sizes rather than calculating them as it does now.

**Comment by beaudet** [comment]
Bam!

**Comment by ruven** [comment]
I've just added the ability of both the IIIF and IIP protocols to request and parse a full list of available image resolutions. The viewer should now handle arbitrary rounding. For IIP, this requires use of the latest iipsrv development code and you will need to activate this feature in the viewer by setting the following immediately after creating your iipmooviewer object:

`iipmooviewer.protocol.ask_resolutions = true;`
